package com.shubham.agentui

import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.JsonPrimitive
import kotlinx.serialization.json.buildJsonArray
import kotlinx.serialization.json.buildJsonObject
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.jsonPrimitive
import kotlinx.serialization.json.put
import kotlinx.serialization.json.putJsonObject
import org.junit.Assert.assertEquals
import org.junit.Assert.assertNotNull
import org.junit.Assert.assertNull
import org.junit.Assert.assertTrue
import org.junit.Test

class A2UiRuntimeTest {
    private val json = Json { ignoreUnknownKeys = true }

    @Test
    fun messagesUseA2UiV09BasicCatalog() {
        val envelope = json.parseToJsonElement(A2UiMessages.createSurface("ai_surface")).jsonObject
        val payload = envelope.getValue("createSurface").jsonObject

        assertEquals("v0.9", envelope.getValue("version").jsonPrimitive.content)
        assertEquals(A2UiMessages.BasicCatalogId, payload.getValue("catalogId").jsonPrimitive.content)
    }

    @Test
    fun componentUpdatesAreIncremental() {
        val runtime = A2UiRuntime()
        val surfaceId = "ai_surface"

        runtime.processMessage(A2UiMessages.createSurface(surfaceId))
        runtime.processMessage(
            A2UiMessages.updateComponents(
                surfaceId,
                listOf(testComponent("root", "Column", "children" to children("title")))
            )
        )
        runtime.processMessage(
            A2UiMessages.updateComponents(
                surfaceId,
                listOf(testComponent("title", "Text", "text" to JsonPrimitive("Generated by AI")))
            )
        )

        assertNotNull(runtime.component(surfaceId, "root"))
        assertNotNull(runtime.component(surfaceId, "title"))
    }

    @Test
    fun missingDataModelValueDeletesExistingPath() {
        val runtime = A2UiRuntime()
        val surfaceId = "ai_surface"

        runtime.processMessage(A2UiMessages.createSurface(surfaceId))
        runtime.processMessage(
            A2UiMessages.updateDataModel(
                surfaceId,
                "/",
                buildJsonObject {
                    putJsonObject("agent") {
                        put("status", "ready")
                        put("mode", "dynamic-ui")
                    }
                }
            )
        )
        runtime.processMessage(updateDataModelWithoutValue(surfaceId, "/agent/status"))

        val agent = runtime.dataSnapshot(surfaceId).getValue("agent").jsonObject
        assertNull(agent["status"])
        assertEquals("dynamic-ui", agent.getValue("mode").jsonPrimitive.content)
    }

    @Test
    fun deleteSurfaceRemovesSurfaceAndDataModel() {
        val runtime = A2UiRuntime()
        val surfaceId = "ai_surface"

        runtime.processMessages(
            listOf(
                A2UiMessages.createSurface(surfaceId),
                A2UiMessages.updateDataModel(surfaceId, "/", buildJsonObject { put("ready", true) }),
                A2UiMessages.updateComponents(surfaceId, listOf(testComponent("root", "Text")))
            )
        )
        runtime.processMessage(A2UiMessages.deleteSurface(surfaceId))

        assertNull(runtime.surfaces[surfaceId])
        assertEquals(JsonObject(emptyMap()), runtime.dataSnapshot(surfaceId))
    }

    @Test
    fun bootstrapComponentsStayWithinSupportedBasicCatalogSubset() {
        val components = TodoAgent()
            .bootstrapMessages()
            .map { json.parseToJsonElement(it).jsonObject }
            .first { "updateComponents" in it }
            .getValue("updateComponents")
            .jsonObject
            .getValue("components")
            .let { it as kotlinx.serialization.json.JsonArray }
            .map { it.jsonObject }

        val allowedKeys = mapOf(
            "Column" to setOf("id", "component", "children", "justify", "align", "weight"),
            "Row" to setOf("id", "component", "children", "justify", "align", "weight"),
            "Card" to setOf("id", "component", "child", "weight"),
            "Text" to setOf("id", "component", "text", "variant", "weight"),
            "TextField" to setOf("id", "component", "label", "value", "variant", "checks", "validationRegexp", "weight"),
            "Button" to setOf("id", "component", "child", "variant", "action", "checks", "weight"),
            "CheckBox" to setOf("id", "component", "label", "value", "action", "checks", "weight"),
            "List" to setOf("id", "component", "children", "direction", "align", "weight")
        )

        components.forEach { component ->
            val componentName = component.getValue("component").jsonPrimitive.content
            val keys = component.keys

            assertTrue("Unsupported component $componentName", componentName in allowedKeys)
            val allowed = allowedKeys.getValue(componentName)
            assertTrue(
                "Unexpected keys for $componentName: ${keys - allowed}",
                keys.all { it in allowed }
            )
        }
    }

    private fun testComponent(
        id: String,
        component: String,
        vararg attrs: Pair<String, kotlinx.serialization.json.JsonElement>
    ): JsonObject {
        return buildJsonObject {
            put("id", id)
            put("component", component)
            attrs.forEach { (key, value) -> put(key, value) }
        }
    }

    private fun children(vararg ids: String) = buildJsonArray {
        ids.forEach { add(JsonPrimitive(it)) }
    }

    private fun updateDataModelWithoutValue(surfaceId: String, path: String): String {
        return buildJsonObject {
            put("version", "v0.9")
            putJsonObject("updateDataModel") {
                put("surfaceId", surfaceId)
                put("path", path)
            }
        }.toString()
    }
}
